### PR TITLE
FIX: Add :via for get and post http methods

### PR DESCRIPTION
**Pull request by yukoff**
Tested on redmine 3.0-stable (3.0.1), it works with this fix - you can update readme accordingly

### CODE REVIEW

**Comment by alexbevi** [comment]
Thanks for the patch @yukoff. I'll just run some a quick regression test (against 2.5/2.6) when i have a second then get this merged.

**Comment by yukoff** [comment]
Hi @alexbevi! Recently tested this with redmine-3.2.0-stable@ruby-2.3.0 - without issues. BTW, there's a typo in version (init.rb) - 2.1.0 vs. 2.2.0 described on plugin page @redmine.org site ;)

**Comment by eckucukoglu** [comment]
Also works fine w/ redmine 3.3-stable.

**Comment by yukoff** [comment]
@alexbevi Is this project alive?

**Comment by alexbevi** [comment]
Sorry @yukoff, I haven't been supporting this project for some time now.

I've merged your PR though (which I should have done 2 years ago :P)

**Comment by yukoff** [comment]
Thanks, @alexbevi! :)

**Comment by alexbevi** [comment]
@yukoff I don't really use Redmine much nowadays. If this plugin is still useful for you and you'd like to be a maintainer, let me know and i'll get you access.

**Comment by yukoff** [comment]
@alexbevi I see :) That would be perfect.

**Comment by yukoff** [comment]
BTW, @alexbevi don't you know how to update corresponding [plugin page](https://www.redmine.org/plugins/redmine_dropbox_attachments) in redmine plugins directory? I've tagged v2.2.1

**Comment by yukoff** [comment]
It should also set compatibility for 2.x-3.x

**Comment by alexbevi** [comment]
@yukoff done and done. If you want to discuss anything related to this plugin, just shoot me an email (alex@alexbevi.com). We'll likely need to upgrade the dropbox code as they're deprecating API v1 and I think that's what we're using

**Pull request merged**
